name=I2C Text Scroller
version=0.1.0
author=Sirawit Jampa
maintainer=Sirawit Jampa
sentence=A simple I2C text scroller.
paragraph= The library handles text sc.
category=Display
url=https://github.com/nomsiae/I2CTextScroller
architectures=*
